version: "3"
services:
    server:
        build: .
        environment:
            - "REDIS_ADDRESS=redis:6379"
            - "WORKERS=8"
            - "CHUNK_SIZE=8000"
        ports:
            - "8000:8000"
        depends_on: 
            - redis
    redis:
        container_name: redis
        image: redis:latest